server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/  

spring:
  application:
    name: bookmark-service
  data:
     mongodb:
        host: 172.16.12.27
        prot: 27017
        database: springcloud
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
        
#用于配置测试  
name: graves     

