server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  
spring:
  application:
    name: favorite-service
  data:
     mongodb:
        host: 172.16.12.27
        prot: 27017
        database: springcloud
       
#暴露配置刷新接口 刷新配置地址为：http://localhost:8020/actuator/refresh  post请求
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
#用于配置测试
name: graves
