server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
      name: gateway
  redis:
    host: 172.16.0.36
    port: 6379
  cloud:
    gateway:
      routes:
      - id: feign
        uri: lb://feign
        #lb:lb代表从注册中心获取服务，后面接需要转发到的服务名称，这个服务名称必须跟eureka中的对应
        predicates:
          - Path=/*/**
        # /*/** 匹配 路由为 /bookmark/getBookmarkList、 /favorite/getFavoriteList 等请求
        filters:
        - name: RequestRateLimiter
          #filter名称必须是RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
            key-resolver: "#{@ipKeyResolver}"
            #redis-rate-limiter.replenishRate：允许用户每秒处理多少个请求
            #redis-rate-limiter.burstCapacity：令牌桶的容量，允许在一秒钟内完成的最大请求数
            #key-resolver：使用SpEL按名称引用bean


