server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
      name: api-gateway
  cloud:
    gateway:
      routes:
      - id: feign
        uri: lb://feign
        #lb:lb代表从注册中心获取服务，后面接需要转发到的服务名称，这个服务名称必须跟eureka中的对应
        predicates:
          - Path=/*/**
        # /*/** 匹配 路由为 /bookmark/getBookmarkList、 /favorite/getFavoriteList 等请求
        

