server:
  port: 8040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/  

spring:
  application:
    name: reminder-service
  data:
     mongodb:
        host: 172.16.12.27
        prot: 27017
        database: springcloud
#暴露接口
management:
  security:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        
#用于配置测试  
name: graves

